#!/usr/bin/env bash
# Generate the Python-side RLN artifacts for the bindings package:
#   1. bindings/python/rln_types.py  — pydantic v2 models (datamodel-codegen),
#      mirroring kaleido-sdk's generate_python_sdk_models.sh flags.
#   2. bindings/uniffi.toml           — maps each FFI boundary type to its
#      pydantic class so Python callers get typed objects (the "#2" mechanism).
#
# The boundary-type list is parsed from the `json_ffi_types!` block in
# bindings/src/rln.rs, so that Rust file stays the single source of truth.
#
# Requires: uv (for uvx), python3. Run with: make generate-rln-pydantic
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SPEC="$ROOT_DIR/specs/rgb-lightning-node.yaml"
MODELS="$ROOT_DIR/bindings/python/rln_types.py"
RLN_RS="$ROOT_DIR/bindings/src/rln.rs"
UNIFFI_TOML="$ROOT_DIR/bindings/uniffi.toml"

command -v uvx >/dev/null 2>&1 || {
  echo "❌ uvx (uv) not found. Install: curl -LsSf https://astral.sh/uv/install.sh | sh" >&2
  exit 1
}

echo "→ Generating pydantic models → bindings/python/rln_types.py"
uvx --from "datamodel-code-generator[ruff]" datamodel-codegen \
  --input "$SPEC" --output "$MODELS" \
  --input-file-type openapi --output-model-type pydantic_v2.BaseModel \
  --use-standard-collections --use-annotated --use-schema-description \
  --field-constraints --snake-case-field --strict-nullable \
  --enum-field-as-literal one --capitalise-enum-members \
  --target-python-version 3.11 --use-double-quotes --collapse-root-models \
  --use-title-as-name --disable-timestamp \
  --custom-file-header "# AUTO-GENERATED by datamodel-codegen from specs/rgb-lightning-node.yaml. Do not edit." \
  --formatters ruff-format 2>&1 | grep -vE "FutureWarning|warn_deprecated" || true

echo "→ Rebuilding bindings/uniffi.toml custom_types mapping"
RLN_RS="$RLN_RS" MODELS="$MODELS" UNIFFI_TOML="$UNIFFI_TOML" python3 - <<'PY'
import os, re

rln_rs = open(os.environ["RLN_RS"]).read()
# Extract the identifiers inside the `json_ffi_types!( ... );` invocation.
block = re.search(r"json_ffi_types!\((.*?)\);", rln_rs, re.S).group(1)
rust_types = re.findall(r"\b([A-Z]\w+)\b", block)

py_names = re.findall(r"^class (\w+)", open(os.environ["MODELS"]).read(), re.M)
by_lower = {}
for n in py_names:
    by_lower.setdefault(n.lower(), n)

MOD = "rln_types"
out = [
    "[bindings.python]",
    'cdylib_name = "kaleidoswap_sdk"',
    "",
    "# --- RLN custom-type mapping (the #2 mechanism) --------------------------",
    "# AUTO-GENERATED by scripts/gen-rln-pydantic.sh — do not edit by hand.",
    "# RLN types cross the FFI as JSON (see bindings/src/rln.rs) and are mapped to",
    "# the locally-bundled pydantic models (bindings/python/rln_types.py). Section",
    "# key = Rust/uniffi type name; into_custom references the pydantic class",
    "# (acronym casing may differ, e.g. LnInvoiceRequest -> LNInvoiceRequest).",
]
missing = []
for t in rust_types:
    py = by_lower.get(t.lower())
    if not py:
        missing.append(t)
        continue
    out += [
        "",
        f"[bindings.python.custom_types.{t}]",
        f'imports = ["{MOD}"]',
        f'into_custom = "{MOD}.{py}.model_validate_json({{}})"',
        'from_custom = "{}.model_dump_json()"',
    ]
open(os.environ["UNIFFI_TOML"], "w").write("\n".join(out) + "\n")
print(f"   mapped {len(rust_types) - len(missing)}/{len(rust_types)} boundary types")
if missing:
    raise SystemExit(f"❌ no pydantic class for: {missing}")
PY

echo "✅ RLN Python artifacts regenerated"
